language: C
dist: trusty
before_install:
  - git clone https://bitbucket.org/UBERTC/aarch64-linux-android-4.9-kernel toolchain
  - export CROSS_COMPILE=$PWD/toolchain/bin/aarch64-linux-android-
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential kernel-package libncurses5-dev bzip2
  - chmod +x Build.sh
  - chmod +x $PWD/tools/dct/DrvGen.py

# we're not installing anything
install: true

script:
  - ./Build.sh

deploy:
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_MOTO"
  file: "$PWD/out/arch/arm64/boot/Image.gz-dtb"
  skip_cleanup: true
  on:
    tags: true
all_branches: true
